# Generated by Django 5.2.4 on 2025-09-22 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
    ]
