# Generated by Django 5.2.4 on 2025-08-25 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='isDeleted',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 25, 10, 45, 48, 706478, tzinfo=datetime.timezone.utc)),
        ),
    ]
