# Generated by Django 5.2.4 on 2025-09-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_board_isdeleted_alter_board_createdat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
