# Generated by Django 5.2.4 on 2025-09-22 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreg',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='userreg',
            table='userreg',
        ),
        migrations.AlterModelTable(
            name='usertoken',
            table='usertoken',
        ),
    ]
